kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-health-check
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-health-check
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: nfs-health-check
          image: aixeshunter/nfs-health-check:v1.1
          env:
            - name: NFS_SERVER
              value: 127.0.0.1
            - name: NFS_PATH
              value: /opt/nfs
